

PKG_NAME = glib
PKG_VERS = 2.30
PKG_EXT = tar.bz2
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).2.$(PKG_EXT)
PKG_DIST_SITE = ftp://ftp.gtk.org/pub/$(PKG_NAME)/$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS).2

DEPENDS = 

MAINTAINER = fixme
HOMEPAGE   = fixme
COMMENT    = fixme
LICENSE    = fixme

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
