
PKG_NAME = irssi
PKG_VERS = 0.8.15
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://irssi.org/files
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

MAINTAINER = fixme
HOMEPAGE   = fixme
COMMENT    = fixme
LICENSE    = fixme

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --disable-glibtest

ADDITIONAL_CFLAGS =

include ../../mk/spksrc.cross-cc.mk
